apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: raseed-web
  annotations:
    run.googleapis.com/ingress: all
    autoscaling.knative.dev/minScale: "0"
    autoscaling.knative.dev/maxScale: "20"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/raseed-web:latest
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "PROJECT_ID"
        - name: BACKEND_URL
          value: "https://raseed-backend-PROJECT_ID.a.run.app"
        - name: FLUTTER_WEB_BASE_HREF
          value: "/"
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10 